#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("cnn_input_Addr_A", 32, hls_out, 0, "bram", "MemPortADDR2", 1),
	Port_Property("cnn_input_EN_A", 1, hls_out, 0, "bram", "MemPortCE2", 1),
	Port_Property("cnn_input_WEN_A", 4, hls_out, 0, "bram", "MemPortWE2", 1),
	Port_Property("cnn_input_Din_A", 32, hls_out, 0, "bram", "MemPortDIN2", 1),
	Port_Property("cnn_input_Dout_A", 32, hls_in, 0, "bram", "MemPortDOUT2", 1),
	Port_Property("cnn_input_Clk_A", 1, hls_out, 0, "bram", "mem_clk", 1),
	Port_Property("cnn_input_Rst_A", 1, hls_out, 0, "bram", "mem_rst", 1),
	Port_Property("prediction_address0", 4, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("prediction_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("prediction_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("prediction_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("s_axi_CRTL_BUS_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CRTL_BUS_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "cnn";
