// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv_2_HH_
#define _conv_2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "conv_2_fadd_32ns_cud.h"
#include "conv_2_fmul_32ns_dEe.h"
#include "conv_2_fcmp_32ns_eOg.h"
#include "conv_2_conv_2_bias.h"
#include "conv_2_conv_2_weibkb.h"

namespace ap_rtl {

struct conv_2 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > max_pool_1_out_address0;
    sc_out< sc_logic > max_pool_1_out_ce0;
    sc_in< sc_lv<32> > max_pool_1_out_q0;
    sc_out< sc_lv<13> > conv_out_address0;
    sc_out< sc_logic > conv_out_ce0;
    sc_out< sc_logic > conv_out_we0;
    sc_out< sc_lv<32> > conv_out_d0;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<5> > ap_var_for_const2;


    // Module declarations
    conv_2(sc_module_name name);
    SC_HAS_PROCESS(conv_2);

    ~conv_2();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    conv_2_conv_2_bias* conv_2_bias_U;
    conv_2_conv_2_weibkb* conv_2_weights_U;
    conv_2_fadd_32ns_cud<1,2,32,32,32>* conv_2_fadd_32ns_cud_U1;
    conv_2_fmul_32ns_dEe<1,2,32,32,32>* conv_2_fmul_32ns_dEe_U2;
    conv_2_fcmp_32ns_eOg<1,1,32,32,1>* conv_2_fcmp_32ns_eOg_U3;
    sc_signal< sc_lv<13> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<6> > conv_2_bias_address0;
    sc_signal< sc_logic > conv_2_bias_ce0;
    sc_signal< sc_lv<32> > conv_2_bias_q0;
    sc_signal< sc_lv<15> > conv_2_weights_address0;
    sc_signal< sc_logic > conv_2_weights_ce0;
    sc_signal< sc_lv<32> > conv_2_weights_q0;
    sc_signal< sc_lv<7> > add_ln9_fu_275_p2;
    sc_signal< sc_lv<7> > add_ln9_reg_674;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<4> > r_fu_287_p2;
    sc_signal< sc_lv<4> > r_reg_682;
    sc_signal< sc_lv<4> > c_fu_299_p2;
    sc_signal< sc_lv<4> > c_reg_690;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<14> > zext_ln15_fu_323_p1;
    sc_signal< sc_lv<14> > zext_ln15_reg_695;
    sc_signal< sc_lv<1> > icmp_ln12_fu_293_p2;
    sc_signal< sc_lv<7> > f_fu_333_p2;
    sc_signal< sc_lv<7> > f_reg_703;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<13> > conv_out_addr_reg_708;
    sc_signal< sc_lv<1> > icmp_ln15_fu_327_p2;
    sc_signal< sc_lv<16> > zext_ln39_1_fu_358_p1;
    sc_signal< sc_lv<16> > zext_ln39_1_reg_718;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > conv_2_bias_load_reg_723;
    sc_signal< sc_lv<2> > wr_fu_372_p2;
    sc_signal< sc_lv<2> > wr_reg_731;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<6> > sext_ln31_fu_400_p1;
    sc_signal< sc_lv<6> > sext_ln31_reg_736;
    sc_signal< sc_lv<1> > icmp_ln19_fu_366_p2;
    sc_signal< sc_lv<8> > mul_ln31_fu_414_p2;
    sc_signal< sc_lv<8> > mul_ln31_reg_741;
    sc_signal< sc_lv<1> > icmp_ln33_fu_420_p2;
    sc_signal< sc_lv<1> > icmp_ln33_reg_746;
    sc_signal< sc_lv<2> > wc_fu_436_p2;
    sc_signal< sc_lv<2> > wc_reg_754;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<10> > tmp_10_fu_455_p3;
    sc_signal< sc_lv<10> > tmp_10_reg_759;
    sc_signal< sc_lv<1> > icmp_ln22_fu_430_p2;
    sc_signal< sc_lv<14> > zext_ln33_fu_486_p1;
    sc_signal< sc_lv<14> > zext_ln33_reg_764;
    sc_signal< sc_lv<1> > icmp_ln33_1_fu_490_p2;
    sc_signal< sc_lv<1> > icmp_ln33_1_reg_769;
    sc_signal< sc_lv<6> > ch_fu_502_p2;
    sc_signal< sc_lv<6> > ch_reg_777;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > icmp_ln27_fu_542_p2;
    sc_signal< sc_lv<1> > icmp_ln27_reg_782;
    sc_signal< sc_lv<1> > icmp_ln25_fu_496_p2;
    sc_signal< sc_lv<1> > and_ln33_1_fu_600_p2;
    sc_signal< sc_lv<1> > and_ln33_1_reg_797;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > select_ln27_fu_608_p3;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > grp_fu_252_p2;
    sc_signal< sc_lv<32> > grp_fu_248_p2;
    sc_signal< sc_lv<32> > w_sum_reg_821;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<4> > r_0_reg_165;
    sc_signal< sc_lv<7> > phi_mul_reg_177;
    sc_signal< sc_lv<4> > c_0_reg_189;
    sc_signal< sc_lv<1> > icmp_ln9_fu_281_p2;
    sc_signal< sc_lv<7> > f_0_reg_201;
    sc_signal< sc_lv<2> > wr_0_reg_213;
    sc_signal< sc_lv<2> > wc_0_reg_225;
    sc_signal< sc_lv<6> > ch_0_reg_237;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<64> > zext_ln39_3_fu_353_p1;
    sc_signal< sc_lv<64> > zext_ln31_fu_339_p1;
    sc_signal< sc_lv<64> > zext_ln31_8_fu_574_p1;
    sc_signal< sc_lv<64> > zext_ln31_9_fu_584_p1;
    sc_signal< sc_lv<32> > w_sum_1_fu_110;
    sc_signal< sc_lv<32> > grp_fu_248_p0;
    sc_signal< sc_lv<32> > grp_fu_248_p1;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<7> > zext_ln39_fu_305_p1;
    sc_signal< sc_lv<7> > add_ln39_fu_309_p2;
    sc_signal< sc_lv<13> > tmp_9_fu_315_p3;
    sc_signal< sc_lv<14> > zext_ln39_2_fu_344_p1;
    sc_signal< sc_lv<14> > add_ln39_1_fu_348_p2;
    sc_signal< sc_lv<4> > tmp_s_fu_382_p3;
    sc_signal< sc_lv<5> > zext_ln31_2_fu_390_p1;
    sc_signal< sc_lv<5> > zext_ln31_1_fu_378_p1;
    sc_signal< sc_lv<5> > sub_ln31_fu_394_p2;
    sc_signal< sc_lv<4> > zext_ln19_fu_362_p1;
    sc_signal< sc_lv<4> > add_ln31_fu_404_p2;
    sc_signal< sc_lv<4> > mul_ln31_fu_414_p0;
    sc_signal< sc_lv<6> > zext_ln31_4_fu_442_p1;
    sc_signal< sc_lv<6> > add_ln31_2_fu_446_p2;
    sc_signal< sc_lv<5> > trunc_ln31_fu_451_p1;
    sc_signal< sc_lv<4> > zext_ln22_fu_426_p1;
    sc_signal< sc_lv<4> > add_ln31_1_fu_463_p2;
    sc_signal< sc_lv<8> > zext_ln31_6_fu_469_p1;
    sc_signal< sc_lv<8> > add_ln31_3_fu_473_p2;
    sc_signal< sc_lv<13> > tmp_11_fu_478_p3;
    sc_signal< sc_lv<2> > trunc_ln27_fu_508_p1;
    sc_signal< sc_lv<2> > or_ln27_fu_512_p2;
    sc_signal< sc_lv<3> > tmp_3_fu_518_p4;
    sc_signal< sc_lv<2> > or_ln27_2_fu_528_p2;
    sc_signal< sc_lv<5> > or_ln27_1_fu_534_p3;
    sc_signal< sc_lv<10> > zext_ln31_5_fu_548_p1;
    sc_signal< sc_lv<10> > add_ln31_4_fu_556_p2;
    sc_signal< sc_lv<16> > tmp_17_cast_fu_561_p3;
    sc_signal< sc_lv<16> > add_ln31_5_fu_569_p2;
    sc_signal< sc_lv<14> > zext_ln31_7_fu_552_p1;
    sc_signal< sc_lv<14> > add_ln31_6_fu_579_p2;
    sc_signal< sc_lv<1> > icmp_ln33_2_fu_589_p2;
    sc_signal< sc_lv<1> > and_ln33_fu_595_p2;
    sc_signal< sc_lv<32> > bitcast_ln38_fu_616_p1;
    sc_signal< sc_lv<8> > tmp_7_fu_620_p4;
    sc_signal< sc_lv<23> > trunc_ln38_fu_630_p1;
    sc_signal< sc_lv<1> > icmp_ln38_1_fu_640_p2;
    sc_signal< sc_lv<1> > icmp_ln38_fu_634_p2;
    sc_signal< sc_lv<1> > or_ln38_fu_646_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_259_p2;
    sc_signal< sc_lv<1> > and_ln38_fu_652_p2;
    sc_signal< sc_lv<13> > ap_NS_fsm;
    sc_signal< sc_lv<8> > mul_ln31_fu_414_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<13> ap_ST_fsm_state1;
    static const sc_lv<13> ap_ST_fsm_state2;
    static const sc_lv<13> ap_ST_fsm_state3;
    static const sc_lv<13> ap_ST_fsm_state4;
    static const sc_lv<13> ap_ST_fsm_state5;
    static const sc_lv<13> ap_ST_fsm_state6;
    static const sc_lv<13> ap_ST_fsm_state7;
    static const sc_lv<13> ap_ST_fsm_state8;
    static const sc_lv<13> ap_ST_fsm_state9;
    static const sc_lv<13> ap_ST_fsm_state10;
    static const sc_lv<13> ap_ST_fsm_state11;
    static const sc_lv<13> ap_ST_fsm_state12;
    static const sc_lv<13> ap_ST_fsm_state13;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<7> ap_const_lv7_B;
    static const sc_lv<4> ap_const_lv4_B;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<8> ap_const_lv8_D;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<6> ap_const_lv6_1F;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_add_ln31_1_fu_463_p2();
    void thread_add_ln31_2_fu_446_p2();
    void thread_add_ln31_3_fu_473_p2();
    void thread_add_ln31_4_fu_556_p2();
    void thread_add_ln31_5_fu_569_p2();
    void thread_add_ln31_6_fu_579_p2();
    void thread_add_ln31_fu_404_p2();
    void thread_add_ln39_1_fu_348_p2();
    void thread_add_ln39_fu_309_p2();
    void thread_add_ln9_fu_275_p2();
    void thread_and_ln33_1_fu_600_p2();
    void thread_and_ln33_fu_595_p2();
    void thread_and_ln38_fu_652_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_bitcast_ln38_fu_616_p1();
    void thread_c_fu_299_p2();
    void thread_ch_fu_502_p2();
    void thread_conv_2_bias_address0();
    void thread_conv_2_bias_ce0();
    void thread_conv_2_weights_address0();
    void thread_conv_2_weights_ce0();
    void thread_conv_out_address0();
    void thread_conv_out_ce0();
    void thread_conv_out_d0();
    void thread_conv_out_we0();
    void thread_f_fu_333_p2();
    void thread_grp_fu_248_p0();
    void thread_grp_fu_248_p1();
    void thread_icmp_ln12_fu_293_p2();
    void thread_icmp_ln15_fu_327_p2();
    void thread_icmp_ln19_fu_366_p2();
    void thread_icmp_ln22_fu_430_p2();
    void thread_icmp_ln25_fu_496_p2();
    void thread_icmp_ln27_fu_542_p2();
    void thread_icmp_ln33_1_fu_490_p2();
    void thread_icmp_ln33_2_fu_589_p2();
    void thread_icmp_ln33_fu_420_p2();
    void thread_icmp_ln38_1_fu_640_p2();
    void thread_icmp_ln38_fu_634_p2();
    void thread_icmp_ln9_fu_281_p2();
    void thread_max_pool_1_out_address0();
    void thread_max_pool_1_out_ce0();
    void thread_mul_ln31_fu_414_p0();
    void thread_mul_ln31_fu_414_p00();
    void thread_mul_ln31_fu_414_p2();
    void thread_or_ln27_1_fu_534_p3();
    void thread_or_ln27_2_fu_528_p2();
    void thread_or_ln27_fu_512_p2();
    void thread_or_ln38_fu_646_p2();
    void thread_r_fu_287_p2();
    void thread_select_ln27_fu_608_p3();
    void thread_sext_ln31_fu_400_p1();
    void thread_sub_ln31_fu_394_p2();
    void thread_tmp_10_fu_455_p3();
    void thread_tmp_11_fu_478_p3();
    void thread_tmp_17_cast_fu_561_p3();
    void thread_tmp_3_fu_518_p4();
    void thread_tmp_7_fu_620_p4();
    void thread_tmp_9_fu_315_p3();
    void thread_tmp_s_fu_382_p3();
    void thread_trunc_ln27_fu_508_p1();
    void thread_trunc_ln31_fu_451_p1();
    void thread_trunc_ln38_fu_630_p1();
    void thread_wc_fu_436_p2();
    void thread_wr_fu_372_p2();
    void thread_zext_ln15_fu_323_p1();
    void thread_zext_ln19_fu_362_p1();
    void thread_zext_ln22_fu_426_p1();
    void thread_zext_ln31_1_fu_378_p1();
    void thread_zext_ln31_2_fu_390_p1();
    void thread_zext_ln31_4_fu_442_p1();
    void thread_zext_ln31_5_fu_548_p1();
    void thread_zext_ln31_6_fu_469_p1();
    void thread_zext_ln31_7_fu_552_p1();
    void thread_zext_ln31_8_fu_574_p1();
    void thread_zext_ln31_9_fu_584_p1();
    void thread_zext_ln31_fu_339_p1();
    void thread_zext_ln33_fu_486_p1();
    void thread_zext_ln39_1_fu_358_p1();
    void thread_zext_ln39_2_fu_344_p1();
    void thread_zext_ln39_3_fu_353_p1();
    void thread_zext_ln39_fu_305_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
