#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("flat_array_0_address0", 6, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_0_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_0_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_1_address0", 6, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_1_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_1_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_2_address0", 6, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_2_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_2_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_3_address0", 6, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_3_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_3_q0", 32, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_4_address0", 6, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_4_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_4_q0", 32, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_5_address0", 6, hls_out, 5, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_5_ce0", 1, hls_out, 5, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_5_q0", 32, hls_in, 5, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_6_address0", 6, hls_out, 6, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_6_ce0", 1, hls_out, 6, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_6_q0", 32, hls_in, 6, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_7_address0", 6, hls_out, 7, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_7_ce0", 1, hls_out, 7, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_7_q0", 32, hls_in, 7, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_8_address0", 6, hls_out, 8, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_8_ce0", 1, hls_out, 8, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_8_q0", 32, hls_in, 8, "ap_memory", "mem_dout", 1),
	Port_Property("flat_array_9_address0", 6, hls_out, 9, "ap_memory", "mem_address", 1),
	Port_Property("flat_array_9_ce0", 1, hls_out, 9, "ap_memory", "mem_ce", 1),
	Port_Property("flat_array_9_q0", 32, hls_in, 9, "ap_memory", "mem_dout", 1),
	Port_Property("dense_out_address0", 6, hls_out, 10, "ap_memory", "mem_address", 1),
	Port_Property("dense_out_ce0", 1, hls_out, 10, "ap_memory", "mem_ce", 1),
	Port_Property("dense_out_we0", 1, hls_out, 10, "ap_memory", "mem_we", 1),
	Port_Property("dense_out_d0", 32, hls_out, 10, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "fully_connected";
